// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9EXPySICLHABuHZ6ZVZKBm83IskhGKyI',
    appId: '1:91505831443:web:c52f5edb857a03c42e99e6',
    messagingSenderId: '91505831443',
    projectId: 'e-commerce-159fc',
    authDomain: 'e-commerce-159fc.firebaseapp.com',
    storageBucket: 'e-commerce-159fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3QId87pehdtesHnPrn33cdU3A28jbeZY',
    appId: '1:91505831443:android:00c62af22643ea162e99e6',
    messagingSenderId: '91505831443',
    projectId: 'e-commerce-159fc',
    storageBucket: 'e-commerce-159fc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9EXPySICLHABuHZ6ZVZKBm83IskhGKyI',
    appId: '1:91505831443:web:f3900f26f832d4b02e99e6',
    messagingSenderId: '91505831443',
    projectId: 'e-commerce-159fc',
    authDomain: 'e-commerce-159fc.firebaseapp.com',
    storageBucket: 'e-commerce-159fc.appspot.com',
  );
}
